all:
  hosts:
    prod_server:
      ansible_host: ssh.dalhe.ai
      ansible_user: root # Replace with the SSH user
      ansible_port: 22
      ansible_ssh_private_key_file: /root/.ssh/ssh_dalhe_ai
  vars:
    ansible_python_interpreter: /usr/bin/python3 # which Python executable to use on the remote host
