all:
  hosts:
    target_host:
      ansible_host: infra.dalhe.ai
      ansible_user: root # Replace with the SSH user
      ansible_port: 22
      ansible_ssh_private_key_file: /root/.ssh/digitalocean_id_ed25519
  vars:
    ansible_python_interpreter: /usr/bin/python3 # which Python executable to use on the remote host
