# # cspell:ignore cmdline, workdir
---
ansible-navigator:
  app: run
  mode: stdout
  playbook-artifact:
    enable: False
  logging:
    level: error
  execution-environment:
    enabled: True
    container-engine: docker
    image: ansible_ee:latest
    pull:
      policy: missing
    volume-mounts:
      # mount the infra.dalhe.ai ssh key at the expected path, as specified by the execution-environment/files/ssh_config
      - src: "~/.ssh/digitalocean_id_ed25519"
        dest: /root/.ssh/infra_dalhe_ai
  ansible:
    inventory:
      help: False
      entries:
        - inventory/hosts.yml
