# # cspell:ignore cmdline, workdir
---
ansible-navigator:
  mode: stdout # Output directly to stdout instead of TUI mode
  playbook-artifact:
    enable: False # Disable generating playbook artifact files
  logging:
    level: error # Only show error-level logs
  execution-environment:
    enabled: True # Enable running within an execution environment container
    container-engine: docker
    image: ansible_ee:latest # Name of the execution environment image to run
    pull:
      policy: missing # Only pull the image if itâ€™s not present locally
    volume-mounts:
      # mount the ssh.dalhe.ai key at the expected path, as specified by the execution-environment/files/ssh_config
      - src: ~/.ssh/digitalocean_id_ed25519
        dest: /root/.ssh/ssh_dalhe_ai
    environment-variables: # the environment variables to forward to the execution-environment container
      pass:
        - PROD_SERVER_IP
        - CLOUDFLARE_TUNNEL_TOKEN
  ansible:
    inventory:
      help: False # Do not show inventory help output
      entries:
        - inventory/hosts.yml # Inventory file to use for playbook runs
