---
backend_container_name: backend
backend_container_port: "{{ lookup('env', 'BACKEND_PORT') }}"
backend_host_port: "{{ lookup('env', 'BACKEND_PORT') }}"
backend_bind_address: 127.0.0.1
backend_env: { PORT: "{{ lookup('env', 'BACKEND_PORT') }}" }
backend_image: "{{ lookup('env', 'BACKEND_IMAGE') }}"
backend_image_tag: "{{ lookup('env', 'BACKEND_IMAGE_TAG') }}"
ghcr_username: "{{ lookup('env', 'GHCR_USERNAME') }}"
ghcr_token: "{{ lookup('env', 'GHCR_TOKEN') }}"
